### ISSUE TITLE
Option sets are shown in list and in data entry showing code rather than name

### ISSUE THREAD

**Issue by russnes** [dhis2/dhis2-android-eventcapture#1]
Option sets are shown in list and in data entry showing the Code rather than the name (possibly needs SDK fix)

**Comment by arazabishov** [comment]
It seems to be a problem on server side. Since all "Mode of Discharge" datavalues in "Inpatient morbidity and mortality program contain code instead of name.
https://apps.dhis2.org/demo/api/events?page=0&pageSize=200&orgUnit=DiszpKrYNg8&program=eBAyeGv0exc&filter=lastUpdated:gt:2015-03-30T04:50:49.462+0000&fields=events[dataValues[value]]

**Comment by russnes** [comment]
Actually it's not, it's the way options and option sets work. For example MODDISCH is the code of an Option in the option set of the given data element, so it's required to do a lookup in the database by this code, and find the Name of the option (eg Mode of Discharge) and a check if a data element is an option set. This is so that in case someone changes the name of an option set we don't get stray values in the database of DHIS 2.

**Comment by arazabishov** [comment]
Yeap, already aware of this design consideration. Added support of option code in latest commit as well as fixed issue with displaying code of option set in SelectProgramFragment.

Will fix this in DataEntryFragment soon.

**Comment by arazabishov** [comment]
Implemented and merged to master branch.
